// <auto-generated />
using MakeCake.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MakeCake.DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221103164033_AddRelationsToBiscuitDTO")]
    partial class AddRelationsToBiscuitDTO
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BiscuitDtoCreamDto", b =>
                {
                    b.Property<int>("BiscuitsId")
                        .HasColumnType("int");

                    b.Property<int>("CreamsId")
                        .HasColumnType("int");

                    b.HasKey("BiscuitsId", "CreamsId");

                    b.HasIndex("CreamsId");

                    b.ToTable("BiscuitDtoCreamDto");
                });

            modelBuilder.Entity("BiscuitDtoFillingDto", b =>
                {
                    b.Property<int>("BiscuitsId")
                        .HasColumnType("int");

                    b.Property<int>("FillingsId")
                        .HasColumnType("int");

                    b.HasKey("BiscuitsId", "FillingsId");

                    b.HasIndex("FillingsId");

                    b.ToTable("BiscuitDtoFillingDto");
                });

            modelBuilder.Entity("MakeCake.DAL.Models.BiscuitDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Biscuits");
                });

            modelBuilder.Entity("MakeCake.DAL.Models.CreamDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Creams");
                });

            modelBuilder.Entity("MakeCake.DAL.Models.FillingDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fillings");
                });

            modelBuilder.Entity("MakeCake.DAL.Models.TierDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BiscuitId")
                        .HasColumnType("int");

                    b.Property<int>("CreamId")
                        .HasColumnType("int");

                    b.Property<int>("Diametr")
                        .HasColumnType("int");

                    b.Property<int>("FillingId")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BiscuitId");

                    b.HasIndex("CreamId");

                    b.HasIndex("FillingId");

                    b.ToTable("Tiers");
                });

            modelBuilder.Entity("BiscuitDtoCreamDto", b =>
                {
                    b.HasOne("MakeCake.DAL.Models.BiscuitDto", null)
                        .WithMany()
                        .HasForeignKey("BiscuitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakeCake.DAL.Models.CreamDto", null)
                        .WithMany()
                        .HasForeignKey("CreamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BiscuitDtoFillingDto", b =>
                {
                    b.HasOne("MakeCake.DAL.Models.BiscuitDto", null)
                        .WithMany()
                        .HasForeignKey("BiscuitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakeCake.DAL.Models.FillingDto", null)
                        .WithMany()
                        .HasForeignKey("FillingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MakeCake.DAL.Models.TierDto", b =>
                {
                    b.HasOne("MakeCake.DAL.Models.BiscuitDto", "Biscuit")
                        .WithMany()
                        .HasForeignKey("BiscuitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakeCake.DAL.Models.CreamDto", "Cream")
                        .WithMany()
                        .HasForeignKey("CreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakeCake.DAL.Models.FillingDto", "Filling")
                        .WithMany()
                        .HasForeignKey("FillingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Biscuit");

                    b.Navigation("Cream");

                    b.Navigation("Filling");
                });
#pragma warning restore 612, 618
        }
    }
}
